# Configurção do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/nome_do_seu_banco
spring.datasource.username=
spring.datasource.password=

# Configuração de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configurações de Fuso Horário
spring.jackson.time-zone=UTC

